# APITesterFor365
name: Test APIs

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "5 */1 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    name: Runs
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests
      run: |
        pip install requests
    - name: Read config from secrets
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
      run: | 
        cp 1.py 2.py
        echo $CONFIG_ID > configid.txt
        echo $CONFIG_KEY > configkey.txt
        sed -i '10 r configid.txt' 2.py
        sed -i '12 r configkey.txt' 2.py
    - name: Test APIs
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python 2.py
    - name: Delete secrets config
      run: | 
        rm -f 2.py
        rm -f configid.txt
        rm -f configkey.txt    
    - name: Commit
      run: |
        git config --global user.email AutoupdateRobot@email.com
        git config --global user.name AutoupdateRobot
        git add .
        git commit -m "Update refresh_token" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
